### ISSUE TITLE
node-sqlite3 is throwing error, does it affect Transcodem?

### ISSUE THREAD

**Issue by nmrony** [madebyhiro/codem-transcode#38]
Hi,
I am trying to install codem-transcode on CentOS 6.5 and getting following error

```sh
[sqlite3] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/node_modules/codem-transcode/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```
I also see an open issue on [here](https://github.com/mapbox/node-sqlite3/issues/244)
Does it affect Transcodem and how to resolve it for CentOS 6.5?

**Comment by tieleman** [comment]
I believe this is similar to this: https://github.com/madebyhiro/codem-transcode/issues/27

This is not an issue with codem-transcode, but with sqlite3/node-gyp. See #27 for a possible solution.
