### ISSUE TITLE
Install depends on old packages and non-existing too

### ISSUE THREAD

**Issue by misiek08** [madebyhiro/codem-transcode#53]
I tried install transocde today, so I wrote npm install codem-transcode and I got at the beginning:

```
transcoder@file78-4-eu:~$ npm install codem-transcode
npm WARN deprecated sequelize@1.6.0: critical security fix in v3.0.0
npm WARN engine sqlite3@2.2.4: wanted: {"node":">= 0.8.0 < 0.13.0"} (current: {"node":"4.2.2","npm":"2.14.7"})
npm WARN deprecated lingo@0.0.5: This project is abandoned
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
```

I wonna use your system on many machines but it won't install :) After many warnings sqlite3 returned error from node-gyp:

```
npm ERR! sqlite3@2.2.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

Installation aborted.

**Comment by misiek08** [comment]
Full log:
```
transcoder@file78-4-eu:~$ npm install codem-transcode
npm WARN deprecated sequelize@1.6.0: critical security fix in v3.0.0
npm WARN engine sqlite3@2.2.4: wanted: {"node":">= 0.8.0 < 0.13.0"} (current: {"node":"4.2.2","npm":"2.14.7"})
npm WARN deprecated lingo@0.0.5: This project is abandoned
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
-
> sqlite3@2.2.4 install /home/transcoder/node_modules/codem-transcode/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c: In function ‘balance’:
Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c:57815:22: warning: array subscript is above array bounds [-Warray-bounds]
         pOld = apCopy[++j];
                      ^
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:335:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
../node_modules/nan/nan.h:335:78: note: candidate is:
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:417:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../node_modules/nan/nan.h:410:3: note: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../node_modules/nan/nan.h:435:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:429:36: note: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:447:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:441:36: note: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:616:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../node_modules/nan/nan.h:616:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../node_modules/nan/nan.h:616:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../node_modules/nan/nan.h:610:36: note: previous declaration ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../node_modules/nan/nan.h:616:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../node_modules/nan/nan.h:616:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../node_modules/nan/nan.h:630:27: error: redefinition of ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Local<T>)’
   NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                           ^
../node_modules/nan/nan.h:625:27: note: ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T>)’ previously declared here
   NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
                           ^
../node_modules/nan/nan.h:878:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:878:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:882:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:882:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:889:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:889:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:172:0,
                 from ../src/database.h:11,
                 from ../src/database.cc:5:
/home/transcoder/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/transcoder/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/transcoder/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/transcoder/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:893:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:900:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../node_modules/nan/nan.h:1973:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:1974:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../node_modules/nan/nan.h:1975:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:1975:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/database.cc:134:71: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
                                                                       ^
../src/database.cc:134:71: note: candidates are:
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/v8.h:23:0,
                 from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2590:26: note: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2590:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2591:37: note: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2591:37: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/v8.h:23:0,
                 from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2595:26: note: bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2595:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2596:37: note: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2596:37: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t {aka unsigned int}’
../src/database.cc:135:69: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Integer>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
                                                                     ^
../src/database.cc:135:69: note: candidates are:
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/v8.h:23:0,
                 from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2590:26: note: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2590:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2591:37: note: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2591:37: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/v8.h:23:0,
                 from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2595:26: note: bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2595:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from /home/transcoder/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../src/database.cc:2:
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2596:37: note: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/transcoder/.node-gyp/4.2.2/include/node/v8.h:2596:37: note:   no known conversion for argument 2 from ‘v8::Local<v8::Integer>’ to ‘uint32_t {aka unsigned int}’
node_sqlite3.target.mk:103: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.4" "--major=2" "--minor=2" "--patch=4" "--runtime=node" "--node_abi=node-v46" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://node-sqlite3.s3.amazonaws.com/" "--module_path=/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/lib/binding/node-v46-linux-x64" "--remote_path=./Release/" "--package_name=node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz" "--staged_tarball=build/stage/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz" "--hosted_path=https://node-sqlite3.s3.amazonaws.com/Release/" "--hosted_tarball=https://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz"
gyp ERR! cwd /home/transcoder/node_modules/codem-transcode/node_modules/sqlite3
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.4 --major=2 --minor=2 --patch=4 --runtime=node --node_abi=node-v46 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://node-sqlite3.s3.amazonaws.com/ --module_path=/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/lib/binding/node-v46-linux-x64 --remote_path=./Release/ --package_name=node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz --staged_tarball=build/stage/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz --hosted_path=https://node-sqlite3.s3.amazonaws.com/Release/ --hosted_tarball=https://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/transcoder/node_modules/codem-transcode/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.4 --major=2 --minor=2 --patch=4 --runtime=node --node_abi=node-v46 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://node-sqlite3.s3.amazonaws.com/ --module_path=/home/transcoder/node_modules/codem-transcode/node_modules/sqlite3/lib/binding/node-v46-linux-x64 --remote_path=./Release/ --package_name=node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz --staged_tarball=build/stage/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz --hosted_path=https://node-sqlite3.s3.amazonaws.com/Release/ --hosted_tarball=https://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.2.4-node-v46-linux-x64.tar.gz' (1)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "codem-transcode"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/transcoder/npm-debug.log
```

**Comment by rubel-metatude** [comment]
I am also facing the same issue.

node v4.2.2
npm  v2.14.11

**Comment by tieleman** [comment]
Aware of the issue, but currently not a lot of time to fix it. I recommend using Node 0.10.x for now which works. The merge with io.js changed things up a bit.
